import type { Metadata } from "next";
import { Inter } from "next/font/google";

import NavigationBar from "./navigationBar";
import { ChakraProvider } from "@chakra-ui/react";
import DarkModeSwitch from "./darkModeSwitcher";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
      <NavigationBar />
      {children}
    </>
  );
}
